### ISSUE TITLE
Bug - Opening a folder deletes the first caption file

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [Nenotriple/img-txt_viewer#25]
Pretty consistently, when I open a folder with existing captions, it deletes the caption from the first file.

It smells like an issue with "Autosave" being true, but I haven't really investigated too much.

Let me know if you are unable to reproduce.

**Comment by Nenotriple** [comment]
I cannot trigger this issue, please list out the steps needed to reproduce it.

**Comment by MNeMoNiCuZ** [comment]
![image](https://github.com/user-attachments/assets/a4a1972d-150b-414e-a836-cfcfdd1fc1b4)
![image](https://github.com/user-attachments/assets/c30399c7-8d56-4e18-bacf-101df90657eb)

It literally deletes the caption of the first image if you have "Auto-save" checked when you open an existing dataset.

If you do the same without "Auto-save" it does not delete the file.
It's likely calling "Save" with an empty text field, before it loads the existing captions, thus overwriting the original caption with nothing, and therefore deleting it.

Sidenote:
I don't know if it's desired to delete the caption when the text is empty. Maybe this could be an option? You may want to have an empty caption file. This is useful in Flux trainings, that can learn well from empty captions, or mixed type captions.

**Comment by Nenotriple** [comment]
This appears to be the same as issue #23, ae56143. In your screenshots, the app is v1.93, the issue is no longer present in the current version. I'm definitely sorry you encountered this bug, it was exactly what you expected was happening.

I always figured images without a text pair would be treated the same as if they had an empty text pair _(e.g., a text file of the same name, without text captions)_. Regardless, I can add an option to prevent text files from being deleted when they're saved blank. I'll also do something to handle the other unpaired images in the working folder.

**Comment by MNeMoNiCuZ** [comment]
Confirmed, it works well in 1.94.
Sorry for not checking latest.

Regarding empty text pairs / deleting files:
I'm not sure which is a better default behavior is more desirable. But it seems worse to delete people's files if they existed, without the user having a say in it. An option does make sense.

I think my UX suggestion is to have deleting be off by default. It's faster to delete a bunch of files than it is to create new empty ones.

This could also be a useful feature, to have it create those empty files as you open a folder. But it may also be getting too niche.

**Comment by Nenotriple** [comment]
`worse to delete people's files if they existed, without the user having a say in it`
This makes complete sense, I'll make the option "Auto-Delete Blank Files" off by default when it's implemented.

I'll consider having the app automatically create text files when you load a directory, but I think it would be best to have this as a tool menu command. I guess it could also be a toggleable option.

**Comment by MNeMoNiCuZ** [comment]
Depending on how much bloat your options get, it may be better as a one-off script.
Personally, a setting sounds better to me if you can afford the space for it :)

**Comment by MNeMoNiCuZ** [comment]
I just encountered this again.
Auto-Delete Blank Files is disabled, and it deleted the first caption in a folder that I loaded, that had captions from before, when I loaded the dataset.

The way I loaded it was to paste the folder path in the folder path-bar, and pressed ENTER. In case that helps.

**Comment by Nenotriple** [comment]
Changing the filepath works a little differently when you use 'enter' compared to the 'browse...' button, so that's probably where the issue's originating.

Hopefully I'll have a fix out this weekend.

**Comment by MNeMoNiCuZ** [comment]
I figured this might be it! Good thing I mentioned it :D

![Image](https://github.com/user-attachments/assets/39bdf682-4d71-4d7a-acc5-51b14f4b0cd3)

I always find the "Enter, Browse or Open" a bit confusing. Not sure what to press :(

Maybe Browse should be on left side, and Open on right side?

Assuming that Open executes on the input path?

**Comment by Nenotriple** [comment]
I can definitely play around with different layouts or text for those widgets.

Basically, "enter/browse" sets the directory, while "open" reveals it in the file explorer.

Maybe changing "browse" to "select" would be clearer?

I'm also thinking of removing the "open" button and just having a single button to select the path.

Something like:

`>_________________`, or `_________________<`,

where the `<`/`>` would be the literal symbol used as the button text. The "open directory in file explorer" command could just be added to the context menu.

**Comment by MNeMoNiCuZ** [comment]
Oh I see! Now I get why the Open button never worked :)

Changing browse to select could make it easier to get. Or "Choose folder" or "Folder picker", but they are less elegant.

I'm personally not fuzzed about the open in explorer-button. I could easily live without it, as if I have a path URL, it's quick for a power user to launch a WIN + R to open it anyway. But I see the shortcut of having it as well, it's not a bad feature.


I did not get your example with the `>________________` 

I assume you meant to just streamline it, and the > symbol (or whichever you end up with), only loads the URL into the program, and that's all?

I think having the option for users to browse folders is nice. I personally dislike it as it's too slow. But I think casual users would just browse to their location.

When it comes to button on left or right side, my preference is on the right. Logically it is this: Path > Execute, this is how the actions are taken, so the interface should also flow like that.


I would suggest a layout like this:

Browse-button on left side, this is an initiation step, so it should come first. As it skips the next step.

Then input path text line.

The button to the immediate right of this path should be the same as pressing enter. It should EXECUTE on path. Whatever that means in your program. In this case, it should mean to load the folder as a dataset, right?

Then, I think an "open path in explorer" button is good as well, but I think I would prefer it as an icon with the explorer folder if that's possible. And a mouse-over explaining "Open in explorer".
This would be furthest to the right and just be small, since it's a luxury feature, not a core feature, if that makes sense.
I would also be fine with this not appearing, until after you have opened it as a dataset. As if I browsed to the folder or pasted the path to it, I likely have it open already, or have no need of going to it.
The benefit of having the "open in explorer"-button to me, is if you leave the program open and continue captioning later, and you want to reopen your path, then I can see some use of it, to "resume" your flow.

So my suggestion if you want to keep all functionality is:
[BROWSE] [INPUT PATH] [OPEN PATH] [LAUNCH IN EXPLORER]

If you cut it short:
[INPUT PATH] [OPEN PATH]


I hope my input wasn't too hard to read, let me know if you want a mockup or something.

**Comment by Nenotriple** [comment]
> I just encountered this again. Auto-Delete Blank Files is disabled, and it deleted the first caption in a folder that I loaded, that had captions from before, when I loaded the dataset.
> 
> The way I loaded it was to paste the folder path in the folder path-bar, and pressed ENTER. In case that helps.

I can't actually reproduce this in v1.97 or v1.96

I tried after a fresh start; pasting a path and pressing enter.

I tried after setting a path via the browse and enter methods.

I tried after restoring the last path.

---

But I did find an issue with the argument positions of `set_working_directory()` *(The command bound to enter)*, where the "event" object was setup as the last argument when it should be the first.

This was causing a error where `check_dir_for_img()` was being handed the event instead of the path, and probably messing with further logic. Every time I tested, it basically just failed the initial scan of the path, but navigating would refresh the file lists. Maybe in some cases that was causing the file to be deleted, but I'm not sure how or why.

---

Please test the v1.97_dev branch and let me know if 5ced96e made any difference for this issue.

**Comment by MNeMoNiCuZ** [comment]
```
Set current directory... OK
settings.cfg found. Enabling FAST_START mode.
Virtual environment activated.
Launching: app.py

C:\AI\Training\img-txt_viewer\app.py:2407: SyntaxWarning: invalid escape sequence '\s'
  text = re.sub(",(?=[^\s])", ", ", text)  # Add a space after a comma if it's not already there
C:\AI\Training\img-txt_viewer\main\scripts\Autocomplete.py:76: SyntaxWarning: invalid escape sequence '\d'
  data_file_path: str = os.path.join(app_path, "main\dict", self.data_file)
C:\AI\Training\img-txt_viewer\main\scripts\Autocomplete.py:119: SyntaxWarning: invalid escape sequence '\d'
  dictionary_file_path: str = os.path.join(self._get_app_path(), "main\dict", self.data_file)
C:\AI\Training\img-txt_viewer\main\scripts\Autocomplete.py:123: SyntaxWarning: invalid escape sequence '\d'
  cache_dir: str = os.path.join(self._get_app_path(), 'main\dict\cache')
Traceback (most recent call last):
  File "C:\AI\Training\img-txt_viewer\app.py", line 74, in <module>
    from main.scripts.video_player_widget import VideoPlayerWidget
  File "C:\AI\Training\img-txt_viewer\main\scripts\video_player_widget.py", line 4, in <module>
    from tkVideoPlayer import TkinterVideo
ModuleNotFoundError: No module named 'tkVideoPlayer'
Launching... FAIL
(venv) C:\AI\Training\img-txt_viewer>uv pip install tkvideoplayer==2.8
Resolved 3 packages in 739ms
error: Failed to prepare distributions
  Caused by: Failed to fetch wheel: av==9.2.0
  Caused by: Build backend failed to determine extra requires with `build_wheel()` with exit code: 1
--- stdout:
Compiling av\logging.pyx because it changed.
[1/1] Cythonizing av\logging.pyx
--- stderr:
performance hint: av\logging.pyx:232:5: Exception check on 'log_callback' will always require the GIL to be acquired.
Possible solutions:
        1. Declare 'log_callback' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
        2. Use an 'int' return type on 'log_callback' to allow an error code to be returned.

Error compiling Cython file:
------------------------------------------------------------
...
cdef const char *log_context_name(void *ptr) nogil:
    cdef log_context *obj = <log_context*>ptr
    return obj.name

cdef lib.AVClass log_class
log_class.item_name = log_context_name
                      ^
------------------------------------------------------------

av\logging.pyx:216:22: Cannot assign type 'const char *(void *) except? NULL nogil' to 'const char *(*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to the type of 'log_context_name'.

Error compiling Cython file:
------------------------------------------------------------
...

# Start the magic!
# We allow the user to fully disable the logging system as it will not play
# nicely with subinterpreters due to FFmpeg-created threads.
if os.environ.get('PYAV_LOGGING') != 'off':
    lib.av_log_set_callback(log_callback)
                            ^
------------------------------------------------------------

av\logging.pyx:351:28: Cannot assign type 'void (void *, int, const char *, va_list) except * nogil' to 'av_log_callback' (alias of 'void (*)(void *, int, const char *, va_list) noexcept nogil'). Exception values are incompatible. Suggest adding 'noexcept' to the type of 'log_callback'.
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Users\user\AppData\Local\uv\cache\builds-v0\.tmpTDdnwc\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\uv\cache\builds-v0\.tmpTDdnwc\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
    self.run_setup()
  File "C:\Users\user\AppData\Local\uv\cache\builds-v0\.tmpTDdnwc\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
    super().run_setup(setup_script=setup_script)
  File "C:\Users\user\AppData\Local\uv\cache\builds-v0\.tmpTDdnwc\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
    exec(code, locals())
  File "<string>", line 157, in <module>
  File "C:\Users\user\AppData\Local\uv\cache\builds-v0\.tmpTDdnwc\Lib\site-packages\Cython\Build\Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
  File "C:\Users\user\AppData\Local\uv\cache\builds-v0\.tmpTDdnwc\Lib\site-packages\Cython\Build\Dependencies.py", line 1321, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: av\logging.pyx
```

**Comment by Nenotriple** [comment]
Nothing special, I just run `Start.bat`, or I launch it from vscode with the local venv selected.

I just did a fresh pull of v1.97_dev and was able to start the app using `Start.bat` without issue.

---

It's definitely strange that you can't manually install `tkvideoplayer`/`av`. And the *SyntaxWarning* is also strange. The code in `cleanup_text()` has probably been unchanged for over a year, and I personally haven't seen any warning or issues with it.

What version of Python are you using? If you're using a newer/older version of Python, there could be some changes that are causing issues.

My system version of Python is 3.10.6, Windows 11

Let me know what version you have installed and I'll test it.

---

The log you provided doesn't show the initial setup and install of the requirements.txt, how did that process go?

Here's my log fwiw:

```
Set current directory... OK
Creating a Python virtual environment: "C:\Users\...\Documents\GitHub\img-txt_viewer\\venv"
Virtual environment created.
Virtual environment activated.
Requirement already satisfied: pip in c:\users\...\documents\github\img-txt_viewer\venv\lib\site-packages (22.2.1)
Collecting pip
  Using cached pip-25.0.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.2.1
    Uninstalling pip-22.2.1:
      Successfully uninstalled pip-22.2.1
Successfully installed pip-25.0.1
WARNING: There was an error checking the latest version of pip.
Installing requirements...
Collecting git+https://github.com/Nenotriple/TkToolTip.git@main (from -r requirements.txt (line 6))
  Cloning https://github.com/Nenotriple/TkToolTip.git (to revision main) to c:\users\...\appdata\local\temp\pip-req-build-17qcr3dy
  Running command git clone --filter=blob:none --quiet https://github.com/Nenotriple/TkToolTip.git 'C:\Users\...\AppData\Local\Temp\pip-req-build-17qcr3dy'
  Resolved https://github.com/Nenotriple/TkToolTip.git to commit 0fdf8c2bedb1cddda5fe0e600da9e90aae430096
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy==2.1.3 (from -r requirements.txt (line 1))
  Downloading numpy-2.1.3-cp310-cp310-win_amd64.whl.metadata (60 kB)
Collecting Pillow==11.0.0 (from -r requirements.txt (line 2))
  Downloading pillow-11.0.0-cp310-cp310-win_amd64.whl.metadata (9.3 kB)
Collecting onnxruntime==1.20.0 (from -r requirements.txt (line 3))
  Downloading onnxruntime-1.20.0-cp310-cp310-win_amd64.whl.metadata (4.6 kB)
Collecting onnxruntime-directml==1.20.1 (from -r requirements.txt (line 4))
  Downloading onnxruntime_directml-1.20.1-cp310-cp310-win_amd64.whl.metadata (4.7 kB)
Collecting tkvideoplayer==2.8 (from -r requirements.txt (line 5))
  Downloading tkvideoplayer-2.8-py3-none-any.whl.metadata (3.2 kB)
Collecting coloredlogs (from onnxruntime==1.20.0->-r requirements.txt (line 3))
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Collecting flatbuffers (from onnxruntime==1.20.0->-r requirements.txt (line 3))
  Downloading flatbuffers-25.2.10-py2.py3-none-any.whl.metadata (875 bytes)
Collecting packaging (from onnxruntime==1.20.0->-r requirements.txt (line 3))
  Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting protobuf (from onnxruntime==1.20.0->-r requirements.txt (line 3))
  Downloading protobuf-6.30.2-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Collecting sympy (from onnxruntime==1.20.0->-r requirements.txt (line 3))
  Downloading sympy-1.13.3-py3-none-any.whl.metadata (12 kB)
Collecting av==9.2.0 (from tkvideoplayer==2.8->-r requirements.txt (line 5))
  Downloading av-9.2.0-cp310-cp310-win_amd64.whl.metadata (4.5 kB)
Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime==1.20.0->-r requirements.txt (line 3))
  Downloading humanfriendly-10.0-py2.py3-none-any.whl.metadata (9.2 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy->onnxruntime==1.20.0->-r requirements.txt (line 3))
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting pyreadline3 (from humanfriendly>=9.1->coloredlogs->onnxruntime==1.20.0->-r requirements.txt (line 3))
  Downloading pyreadline3-3.5.4-py3-none-any.whl.metadata (4.7 kB)
Downloading numpy-2.1.3-cp310-cp310-win_amd64.whl (12.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 1.3 MB/s eta 0:00:00
Downloading pillow-11.0.0-cp310-cp310-win_amd64.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 1.5 MB/s eta 0:00:00
Downloading onnxruntime-1.20.0-cp310-cp310-win_amd64.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 2.5 MB/s eta 0:00:00
Downloading onnxruntime_directml-1.20.1-cp310-cp310-win_amd64.whl (22.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.8/22.8 MB 2.6 MB/s eta 0:00:00
Downloading tkvideoplayer-2.8-py3-none-any.whl (6.2 kB)
Downloading av-9.2.0-cp310-cp310-win_amd64.whl (24.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.4/24.4 MB 3.0 MB/s eta 0:00:00
Downloading coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Downloading flatbuffers-25.2.10-py2.py3-none-any.whl (30 kB)
Downloading packaging-24.2-py3-none-any.whl (65 kB)
Downloading protobuf-6.30.2-cp310-abi3-win_amd64.whl (431 kB)
Downloading sympy-1.13.3-py3-none-any.whl (6.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 2.8 MB/s eta 0:00:00
Downloading humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 2.5 MB/s eta 0:00:00
Downloading pyreadline3-3.5.4-py3-none-any.whl (83 kB)
Building wheels for collected packages: TkToolTip
  Building wheel for TkToolTip (pyproject.toml) ... done
  Created wheel for TkToolTip: filename=tktooltip-1.7-py3-none-any.whl size=5306 sha256=c5345c24d22f54af73891c9379d9b89f2cb27e129b267b856b5d3ba58b8a8b4e
  Stored in directory: C:\Users\...\AppData\Local\Temp\pip-ephem-wheel-cache-b5p41gnz\wheels\20\94\66\1c772f4572194d053d104f016a62b8dfdc29e2a0586c799aac
Successfully built TkToolTip
Installing collected packages: TkToolTip, mpmath, flatbuffers, av, sympy, pyreadline3, protobuf, Pillow, packaging, numpy, tkvideoplayer, humanfriendly, coloredlogs, onnxruntime-directml, onnxruntime
Successfully installed Pillow-11.0.0 TkToolTip-1.7 av-9.2.0 coloredlogs-15.0.1 flatbuffers-25.2.10 humanfriendly-10.0 mpmath-1.3.0 numpy-2.1.3 onnxruntime-1.20.0 onnxruntime-directml-1.20.1 packaging-24.2 protobuf-6.30.2 pyreadline3-3.5.4 sympy-1.13.3 tkvideoplayer-2.8
Launching: app.py
```

**Comment by Nenotriple** [comment]
I've updated the [v1.97b pre-release](https://github.com/Nenotriple/img-txt_viewer/releases/tag/v1.97b) with all the recent changes from v1.97_dev if you want to try that out.

**Comment by MNeMoNiCuZ** [comment]
It was always the auto-save messing it up. Apologies for not labelling this more clearly from the start.
I just realized that this weird "show only thumbnail for 1st image" behavior started some time ago, I think with 1.96. I believe I never had it before. But I did have the removal of the caption before, so maybe there are multiple ways of it happening (some fixed previously), or maybe it's unrelated.

But yes, I can not get it to happen in 1.97.

Now to figure out the dependency nightmare.

Do you need 3.13 for anything else?

3.12 is pretty stable. 3.10 and 3.11 is more common with AI things, so it's not unexpected to require them when it comes to AI or nearby fields.

As long as it's clearly mentioned in the installation steps. Too few projects actually specify which python version is required...

**Comment by Nenotriple** [comment]
>Do you need 3.13 for anything else?

I don't *need* it to be compatible with 3.11+, it would just be nice to avoid situations like this so it's easier for anyone to use.

---

I've changed the README to show `Python 3.10` instead of `Python 3.10+` in the install section.
